### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by fenderle** [xenolf/lego#121]
The command line call gets more and more cluttered, esp. with the addition of the dns solver and its wide variety of configuration through environment variables. 

Wouldn't it be nice to have a structured configuration file to specify the options?

**Comment by mholt** [comment]
You mean like `wss://` in the client and then proxy to a websocket backend? Assuming the websocket app is listening on `localhost:1234`:

```plain
example.com

proxy /websocket_path localhost:1234 {
    websocket
}
```

Did I miss this example in the docs?

**Comment by mholt** [comment]
AFAIK this CLI tool is supposed to stay simple, and using a configuration file makes it easier to make it complicated.

**Comment by fenderle** [comment]
ok - fair enough.

**Comment by lenovouser** [comment]
Hm. I don't know. I fully understand that you want to keep this simple, but I have a ~~s**t~~ load of (sub-)domains right now because LE doesn't support wildcard certificates at the moment. This might change in the future with the DNS challenge, but for now it doesn't work. Currently I use the normal LE client, but I really don't like it and would love to use lego but this kind of keeps me from doing it, as adding / removing domains per command line is going to be really cluttered.

**Comment by lenovouser** [comment]
@mholt cool! Started watching so that I can stalk it :stuck_out_tongue_closed_eyes:

**Comment by lenovouser** [comment]
@mholt any progress? :3

**Comment by mholt** [comment]
No, will work on it later this year. First priority is some Caddy stuff...

**Comment by xenolf** [comment]
@lenovouser We might get a config file for lego after all. The new CLI library the next version will use does have this for free.

**Comment by jojomi** [comment]
Is there any news on this topic? I liked the `acme-client` configuration syntax showed [here](https://noqqe.de/blog/2017/04/22/acme-client/)…
