### ISSUE TITLE
Export getChallenges function

### ISSUE THREAD

**Issue by munnerz** [xenolf/lego#152]
It is not always feasible that the machine requesting the SSL certificate is serving on port 80 and 443 of the domain (eg. in a clustered setup where the incoming requests are load balanced). In order to facilitate this scenario, I want to store the challenge elsewhere to be picked up by whichever instance may be handling the actual HTTP from the ACME server. This is currently not possible with the getChallenges function being an un-exported field.

I propose making this an exported method, so as to allow custom logic when requesting/renewing certificates if necessary.

I'm happy to put in a PR if this proposal is accepted.

**Comment by xenolf** [comment]
Wouldn't this usually get solved by using the DNS-01 challenge if you can't reliably route traffic to the right instance behind a load balancer?

If you can't use DNS-01 for whatever reason - why not create a custom solver which wraps the current HTTP-01 solver and handles the passing around? This way your custom solver gets called for every challenge and is able to decide on a per-challenge basis what to do.

**Comment by janeczku** [comment]
@munnerz Does https://github.com/xenolf/lego/pull/118 solve your problem ?

**Comment by munnerz** [comment]
@xenolf I'll have to look into this as a possibility - to further explain my problem: I need to store the challenge that needs to be served somewhere external (for context, this is within a Kubernetes clusters 'Secret' resource) so that when the HTTP request comes in (which may be served by an entirely separate microservice), it is able to retrieve the correct challenge and respond with that to the ACME server. Then, the microservice that initiated your request (and uses lego to do so) will be able to retrieve the keypair and store it again within the Kubernetes cluster so that it can be used by the ingress.

@janeczku - unfortunately not. The issue isn't with obtaining the certificates, but instead with retrieving the challenge that is used to get the certificate.

**Comment by xenolf** [comment]
So if I'm understanding this right you want to start requesting a cert on one client and have multiple nodes be able to handle the response to the ACME validation request coming from the ACME server. When the validation succeeded the original client should then continue to download the certificate.

This should actually be possible with a custom provider. You receive the challenge in your provider and serialize the token to whatever storage you want. Then you return from the `Present` function and let the client do it's thing which is signalling the ACME server to proceed to validation and then polling the server for a status update. The node receiving the validation request looks at the host header and retrieves the token for the domain and returns that. The original client receives a success message from the ACME server as the validation was successful and requests the certificates.

This does only work for HTTP-01 because you need to do more work in TLS-SNI-01 but that shouldn't be a problem.

**Comment by xenolf** [comment]
@munnerz does the above help you?

**Comment by xenolf** [comment]
I'll close this for now. If there are additional things you would like to discuss, please feel free to re-open the issue again.
