### ISSUE TITLE
Production stability

### ISSUE THREAD

**Issue by codefx9** [xenolf/lego#198]
Hi,
The readme says "This is a work in progress. Please do NOT run this on a production server and please report any bugs you find!" I understand that let's encrypt is very new and all that. I am just curious if there are any known security or design or api stability issues to avoid using this library in production code.

Thanks a lot for this great library.

**Comment by mholt** [comment]
It's pretty good for use in production; the API may change since it's not 1.0 yet, but I definitely don't know of any security flaws in lego that would render it unsafe. I have been using it in production for months without issues. lego is better at handling a lot of the edge cases than other acme clients, considering it supports all 3 challenge types.

**Comment by codefx9** [comment]
Thanks @mholt . 👍

**Comment by mholt** [comment]
That said, if something *does* break in production, you can't say we didn't tell ya so. :wink: Mostly just so people are aware that this isn't a finished product yet.
