### ISSUE TITLE
Staging + Renewal

### ISSUE THREAD

**Issue by pjebs** [xenolf/lego#217]
I used your program (not the code) to create a SSL certificate exactly 3 months ago using this command:
`./lego --email="pj@XXX.com" --domains="abc.CCC.com" run`

It worked well.
Now I am receiving emails on a regular basis from letsencrypt saying I must renew certificate.

My questions:

1. Do I just run that exact command again to renew? Does that mean the renewal process is **exactly** the same as updating certificate?

2. All my emails from letsencrypt say: **You issued a testing cert (not a live one) from Let's Encrypt staging environment** 

What does that mean? I **did not** specify this flag: ` --server=https://acme-staging.api.letsencrypt.org/directory`.
Was this a bug in the program from 3 months ago which has now been updated?

**Comment by xenolf** [comment]
Hello there!

1) You run the same command save for the "run" at the end. This is replaced by "renew". Also if you issued a SAN certificate you only need to pass in the domain listed as "CommonName" in your certificate using the `--domains` switch. Other domains are copied from the existing certificate.

2) The last change to the standard endpoint was on Dec 03 2015 where we switched from staging to the live endpoint. This change happened because the public beta hit. There was no bug here that I am aware of.

If you are using your certificate and it is indeed working, chances are you did not use the staging endpoint. The staging endpoint only issues non-valid certificates.

Is it possible that you ran a test against the staging endpoint with the same email address?

**Comment by pjebs** [comment]
I now strongly believe it is a bug in letsencrypt's end.

The reasons:
1) The certificate was definitely working and used by lots of people. Based on what you told me, it was a live certificate. Plus I did not specify the `--server=https://acme-staging.api.letsencrypt.org/directory` flag.
2) The emails I keep getting keep saying it was a staging certificate.

 Either way, it's now renewed. Thanks :-)
