### ISSUE TITLE
undefined: acme.TLSSNI01ChallengeCertDomain

### ISSUE THREAD

**Issue by sn0bored** [xenolf/lego#225]
I am working on a project using https://github.com/rsc/letsencrypt and when I run

`go get rsc.io/letsencrypt` 

The output I get is:
`# rsc.io/letsencrypt`
`../../../rsc.io/letsencrypt/lets.go:703: undefined: acme.TLSSNI01ChallengeCertDomain`
`../../../rsc.io/letsencrypt/lets.go:716: undefined: acme.TLSSNI01ChallengeCertDomain`

In an attempt to isolate the issue I created a project using only the readme and get the same result.

All my research and work has led me to the interaction with this package.  Is this a dependency that may have changed?

Thanks

**Comment by xenolf** [comment]
Hey and thanks for submitting the issue :)

What version of go do you have installed? The package rsc/letsencrypt uses vendoring to pin it's dependencies to a certain version and it seems like your installation pulled the latest source from here and used that instead of the vendored version.
The latest master in this repository had the symbol you are referring to renamed.

**Comment by sn0bored** [comment]
Wow thanks for the quick response

`go version go1.5.1 darwin/amd64`

**Comment by xenolf** [comment]
IIRC for go 1.5 you need to set the environment variable `GO15VENDOREXPERIMENT=1` before running the go command. As of go 1.6 you no longer need to do that.

**Comment by sn0bored** [comment]
You rock!  Updated to 1.6.2 and that fixed it.

Danke!

**Comment by xenolf** [comment]
Glad you got it working! :)
