### ISSUE TITLE
CloudFlare findTxtRecord inefficient

### ISSUE THREAD

**Issue by jipperinbham** [xenolf/lego#275]
given the current query
```
/zones/%s/dns_records?per_page=1000
```
it's possible to not have a TXT record returned if the total number of records for a zone have more than 1000.

**Comment by porjo** [comment]
pinging @janeczku as the author of that provider. I'd make the change, however I'm not able to test as I don't use Cloudflare. From the [API doco](https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records) looks like it should be as simple as including something like `&type=TXT&name=<acme challenge name>` in the query string

**Comment by janeczku** [comment]
Happy to do the testing if you submit a PR @porjo! There is another issue that could be fixed in the process: We should compare the content of the TXT record against the challenge token, so that when there are multiple records for the FQDN, we only clean up ours.
https://github.com/xenolf/lego/blob/master/providers/dns/cloudflare/cloudflare.go#L148

**Comment by xenolf** [comment]
#276 fixes this issue, doesn't it?

**Comment by janeczku** [comment]
@xenolf Indeed!

**Comment by xenolf** [comment]
Fixed via #276
