### ISSUE TITLE
running it in a production server, too dangerous?

### ISSUE THREAD

**Issue by hanoii** [xenolf/lego#291]
I just setup an automatic renewal on a production server. It is a very restrictive shell and I don't have direct access to the webserver, but this worked very good for only fetching the certificates.

They provide a separate api to update the certs, so once I got the certs everything was fine.

This tool was very useful as the binary worked out of the box and I didn't need any dependency.

However, the quote on the homepage worried me a bit:

> Please do NOT run this on a production server and please report any bugs you find!

I currently don't mind arguments/options changes and besides I am using a built binary, but besides the usual WIP complain, do you have any strong position into running it on a production server?

Thanks!

**Comment by mholt** [comment]
FWIW, [Caddy](https://caddyserver.com) uses the `acme` package underlying the lego CLI in production for tens of thousands of sites and the underlying package is pretty sound. The CLI may be less vetted since it was only meant to be a "testing/experimentation tool" of sorts for the underlying package... but it may work very well for you.

**Comment by xenolf** [comment]
The disclaimer in the README is there to make it clear that the project is not yet "1.0.0" and thus problems *may* arise. Basically just your run-of-the-mill WIP disclaimer :)
