### ISSUE TITLE
Clear pending authorizations on error

### ISSUE THREAD

**Issue by RBeaudoin** [xenolf/lego#353]
Currently, a call to `ObtainCertificateForCSR` makes an initial `POST` to the `new-authz` endpoint prior to calling `Present` on the supplied challenge provider. If an error is returned from `Present`, the authorization stays in a pending state, and there is no mechanism to clear the pending authorization. The actual authorization URI is also not logged or made available which means the pending authorizations cannot be cleared manually.

To prevent hitting up against pending authz rate-limits, lego would need to make the authorization URI available, or provide a mechanism to clear pending authz on errors. The only way we've seen to accomplish this currently is to never return an error from `Present`, and knowingly allow the call to `validate` to fail thus clearing the pending authz request.

**Comment by fxposter** [comment]
@RBeaudoin @xenolf This is not only about `ObtainCertificateForCSR`. It's about all methods that eventually lead to creating authorizations, like `ObtainCertificate` and `RenewCertificate`. Also, it is not only related to challenge provider failures, but to any failures that can happen after the first `new-authz` succeeded request.

IE: if you request one cert for a couple of domains - you will need to create a bunch of authorizations. If the first one is created, while some of the other ones fail - you will "leak" a pending authorizations forever.

Other cases include failing challenge providers, "badNonce" errors from LE, "serverInternal" errors from LE, etc.

I have a working fix for this solution, which you can see here: https://github.com/fxposter/lego/commit/c72f59ad694a440bc419e481db4bb211a413a942.

Basically, what I am doing is always passing `AuthURLs` back to the callers, so that if there are any errors returned from `ObtainCertificate` or `RenewCertificate` - we can pass those AuthURLs to newly created `DeactivatePendingAuthorization` method, which will deactivate all authorizations that are pending based on the AuthURLs.

This is NOT a solution that I like (the API does not look very consistent and `DeactivatePendingAuthorization` is better be splitted into `DeactivateAuthorization` and `FetchAuthorization`), but in that case we would need to expose whole lot of currently internal objects like `authorization`, `identifier`, `challenge`, etc.

@xenolf I did not (yet) made a pull request because of the fact that it breaks the current API. Do you have any ideas how to make it better? Other options may involve moving `AuthURLs` to `CertificateResource` structs (and it is probably what should be done, actually), but what about "problems" with `DeactivatePendingAuthorization`? Also, currently, I am doing deactivation on the client side, not within a library, and maybe it would be better from the API perspective to just deactivate them on failures automatically, but it actually depends on the project's goals - is it a "complete solution" or "building blocks" for other solutions on top of.

**Comment by xenolf** [comment]
Authz URIs should be logged now and lego does clear pending authz on error since f3fc555a985aa70935c129474f30f6825aaf6dd9
