### ISSUE TITLE
dns_challenge.go does not account for delegated auth zones

### ISSUE THREAD

**Issue by rosteroster** [xenolf/lego#361]
dns_challenge.go uses lookupNameservers to find the authoritative nameserver for a given FQDN. That's all well and good. The problem I've run into occurs when that authoritative nameserver is delegating authority to a second nameserver. 
Specifically, in the first nameserver, there is an NS entry in the first nameserver for the given FQDN, pointing to the second nameserver. I'm finding that DNS challenges are failing in this situation as the checkAuthoritativeNss function call only searches for TXT records, it does not handle the case where it encounters an NS entry. The better behavior would be to search the second nameserver for the TXT record.

Information on where to follow the delegation is found in the dnsQuery's response.Ns

**Comment by rosteroster** [comment]
I have a functioning patch for this usecase on my local machine, but I want to know if this is a usecase that lego intends to support @xenolf

**Comment by sajal** [comment]
Just ran into this. (FYI im using the acmev2 branch for wildcard).

Is there an easy way to completely disable `checkAuthoritativeNss` check?

**Comment by fd0** [comment]
I have the same situation as @rosteroster, the `_acme-challenge` subdomain is delegated to a different name server (that I control myself), like this:
```
$ dig _acme-challenge.example.com NS @ns.example.com
[...]
_acme-challenge.example.com. 28800	IN	NS	other.example.com.
```

I just gave the code in the master branch a try and found that unfortunately it still does not handle this situation:
```
$ ./lego '*.example.com' --dns-resolvers 8.8.8.8 --dns exec renew --days 30
2018/12/19 12:41:54 [INFO] [*.example.com] acme: Trying renewal with 254 hours remaining
2018/12/19 12:41:54 [INFO] [*.example.com] acme: Obtaining bundled SAN certificate
2018/12/19 12:41:54 [INFO] [*.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/[...]
2018/12/19 12:41:54 [INFO] [*.example.com] acme: use dns-01 solver
2018/12/19 12:41:54 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2018/12/19 12:41:54 [INFO] [*.example.com] acme: Trying to solve DNS-01
2018/12/19 12:41:54 [INFO] [*.example.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2018/12/19 12:41:54 [INFO] Wait [timeout: 1m0s, interval: 2s]
2018/12/19 12:41:55 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
[...]
2018/12/19 12:42:53 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2018/12/19 12:42:55 acme: Error -> One or more domains had a problem:
[example.com] time limit exceeded: last error: NS ns.example.com. did not return the expected TXT record [fqdn: _acme-challenge.example.com.]
```

So it looks like this issue is not (yet) resolved. For now, I'm using the new `--dns-disable-cp` flag.

Please let me know if there's anything I can do to help!

**Comment by ldez** [comment]
It's the goal of `--dns-disable-cp`: only one nameserver success is required.

**Comment by fd0** [comment]
Hm. As far as I understood the code, it tries to find the authoritative DNS servers and queries them to make sure the record has been installed successfully. 

But in my case (sorry if that's an odd setup, at least I'm pretty sure the delegation is correct), the correct server is never asked: I can see (using tcpdump) that `lego` finds `ns.example.com` as the authoritative server for `example.com` and asks it for the `TXT` record. Since the zone is delegated, the server does not return a response record, but includes the information for the correct nameserver (`other.example.com`) in the response packet. The usual DNS resolvers would then send the request again, to the correct nameserver (`other.example.com`). It appears to me `lego` doesn't do that.

Do I understand that correctly?

I'll try to dig into the code in a bit.

**Comment by fd0** [comment]
Oh, it's my fault, I had a typo in the `SOA` record for `_acme-challenge.example.com` on `other.example.com`, so `lego` (correctly) detected `ns.example.com` as the authoritative nameserver.

Is it maybe a good idea to log which servers were detected and queried in this check?
