### ISSUE TITLE
Error "unexpected authZone" when using Gandi Provider

### ISSUE THREAD

**Issue by fredleger** [xenolf/lego#403]
When trying to generate a certificate using letsencryp ACME challenge i've got the following error.

I traced it down to func 'Present' (https://github.com/xenolf/lego/blob/82ac43327b01319544c050d5d78a4edeff9565d2/providers/dns/gandi/gandi.go#L87 | here) but i'm not sure how this could be fixed.

My zone look as the following for the revelant parts:
```
@ 300 IN A 37.187.4.102
tdm 300 IN A 37.187.4.102
* 300 IN CNAME www.webofmars.com.
www 300 IN CNAME www.webofmars.com.
@ 300 IN MX 50 fb.mail.gandi.net.
@ 300 IN MX 10 spool.mail.gandi.net.
@ 300 IN TXT "v=spf1 ip4:37.187.4.102 ?all"
```

```
letsencrypt-webofmars-fr-letsencrypt-1 | 2017-06-23T11:57:31.243143117Z time="2017-06-23T11:57:31Z" level=error msg="[flphotos.webofmars.fr] Error obtaining certificate: Error presenting token: Gandi DNS: unexpected authZone webofmars.com. for fqdn _acme-challenge.flphotos.webofmars.fr."
letsencrypt-webofmars-fr-letsencrypt-1 | 2017-06-23T11:57:31.243197168Z time="2017-06-23T11:57:31Z" level=error msg="[tdm.webofmars.fr] Error obtaining certificate: Error presenting token: Gandi DNS: unexpected authZone webofmars.com. for fqdn _acme-challenge.tdm.webofmars.fr."
```

**Comment by xi2** [comment]
Hi, and sorry for the delay in replying to your report. Unless I am mistaken the issue is not specific to the Gandi provider, and is caused by your requested certificate domains being CNAMEs that cross zones (from webofmars.fr to webofmars.com). See also issues https://github.com/xenolf/lego/issues/421 and https://github.com/xenolf/lego/issues/330. There is a proposed fix you might try in the second comment of https://github.com/xenolf/lego/issues/421.

Alternatively, you could try adding A/AAAA records for flphotos.webofmars.fr and tdm.webofmars.fr in the webofmars.fr zone.

**Comment by fredleger** [comment]
Humm actually i wasn't trying that. But in Gandi GUI, the zone file used where the same for webofmars.com and webofmars.fr (and other). This is common use with this DNS provider you define a main zone file and use it for many domains, avoiding to multiply the zones files to manage. The webofmars.com message might comes from there.

Since the issue i migrated to Route53 for better reactivity in APIs calls so i can't test anymore but still interested in the issue if revelant. Will try to gather more infos if needed.

Regards

**Comment by fd** [comment]
#449 resolves this issue.
