### ISSUE TITLE
Support Gandi v5 API (Gandi LiveDNS)

### ISSUE THREAD

**Issue by barbare** [xenolf/lego#426]
Gandi has a  [RESTful HTTP API](http://doc.livedns.gandi.net/) for their LiveDNS platform.
The current Gandi support in Lego uses the older API.

**Comment by xi2** [comment]
Thanks for the ping @mholt. I was not aware of the new platform/API and will look at it soon, since I am still using Gandi and Lego.

The old API, and thus Lego, continue to work as long as you have not migrated your DNS over to the LiveDNS system - a choice made by the user when logged in to Gandi's website. However, at some point the old v4 API will go away and users will, presumibly, be forcibly migrated to v5 and LiveDNS.

**Comment by mholt** [comment]
Awesome, thanks. :) Just wanted to loop you in either way.

**Comment by xi2** [comment]
Looking at the PRs now, it seems someone has already done the work at https://github.com/xenolf/lego/pull/365! I will test it when I get a chance.

**Comment by aslafy-z** [comment]
Hi @xi2, it works for me even if it needs some little fixes. You're welcome if you want to resume my pr.

**Comment by okand** [comment]
I just migrated to Gandi because the API for my old registrar and dns provider wasn't doing it (had to pay extra for access) and then got tripped up by this. Didn't realise there were multiple versions and that lego/caddy used the old api new customers at Gandi don't even get the option to use.

**Comment by barbare** [comment]
Resolved in [#365](https://github.com/xenolf/lego/pull/365)

**Comment by jfisbein** [comment]
Hi,
Any plan to make a release with this change included?
Thanks!
