### ISSUE TITLE
Installation from source instructions?

### ISSUE THREAD

**Issue by shurcooL** [xenolf/lego#46]
I think it'd be very helpful to have a section that covers how to install `lego` from source. In the README, I could only see that binary releases are available. If I want to build from source, is that supported?

I _assume_ it would be just `go get -u github.com/xenolf/lego`, but without a section like https://github.com/shurcooL/binstale#installation, I find it hard to be confident.

Leaving this out makes me worry that building from source is not recommended/not supported. Is that the case?

**Comment by mholt** [comment]
It probably depends what you mean by "building from source is supported". If you mean building tip (latest commit on master), then it probably depends what kind of environment you're running it in and the risks you're willing to take. While tip may have more immediate bug fixes, it might not be stable at that point. If you mean building from any untagged commit of the source, then that's probably not a good idea - both old and not stable. If you mean building from any older, tagged commit (i.e. anything but the latest release or checkpoint), that also doesn't seem like a great idea because usually the latest tag will be better.

But all of this is fine if you're just testing it or using it in dev environments. For production, maybe stick the published, pre-built releases?

Is being able to `go get` a Go repo really that unique for Go projects? I think both Sebastian and I kind of assume that Go programmers know how to do this (after all, you need Go installed in order to build the source).

But in the end, probably wouldn't hurt to have that one line in the README...

**Comment by shurcooL** [comment]
> But all of this is fine if you're just testing it or using it in dev environments. For production, maybe stick the published, pre-built releases?

I see. I have no problem doing that, but I didn't know this was the case because the README didn't communicate it to me. I thought it was between this, or you just forgot to include the `go get -u` instructions. This answer answers that, thanks.

> Is being able to go get a Go repo really that unique for Go projects? I think both Sebastian and I kind of assume that Go programmers know how to do this (after all, you need Go installed in order to build the source).

It's easy if you know 2 things:

- The canonical import path matches the URL you're looking at; there's no vanity import path being used.
    - For example, see https://github.com/sourcegraph/go-vcs#installing. Its import path is not something you can easily figure out, unless you look into .go files and find `// import "import/path"` comment; but which .go file to look in? And it might not even have an import path comment.
- The project supports `go get -u`. Some projects do not. For example, some projects rely on `Godeps`, so you need to `go get -d`, then `Godep go build`. Some projects use `gb`. Some projects use Makefile. If I see a project for the first time, I can't be 100% `go get -u` is expected to work unless I see it in the README.

So, having such an installation section answers those 2 things.

> But whatever our philosophy, you're right, it probably wouldn't hurt to have that one line in the README... easy to copy+paste. :smile:

Yep, being able to copy + paste is another, really minor benefit. But it's primarily to communicate that `go get -u` is supported and the canonical import path.

It sounds like you want a "building from source" section that explains that for normal use, binary releases should be used, and building from source is not supported. Building from source is only supported for development uses.
