### ISSUE TITLE
Possible trademark infringement

### ISSUE THREAD

**Issue by lpar** [xenolf/lego#470]
"LEGO" is a registered trademark, and The Lego Group are [interested in enforcing their trademark](https://www.lego.com/en-us/aboutus/news-room/2017/november/lego-trademark-china) outside the realm of toys. They also sell software products for their Mindstorms kits. So it seems to me to be rather risky to use their trademarked name as the name of your project.

I have no connection to Lego Group, just suggesting that you might want to consider a safer name.

**Comment by captncraig** [comment]
Seems like a bit of a stretch to me.

- This is clearly not in the same market. Nobody is going to confuse this with the toys.
- This project has a clear alternate use of those four letters (**L**et's **E**ncrypt **GO**)
- Low risk. Proving damages seems far-fetched. Worst case they send a Cease and Desist, and github delists until it gets renamed. Same net effect as a pre-emptive renaming really, no?

Not a lawyer, but I wouldn't worry about this until it becomes a problem.

**Comment by mholt** [comment]
I agree with Craig. While not a lawyer, I would be surprised (and frankly appalled/disappointed) if that company had any grounds against this project. In addition to Craig's points, this project uses the lowercase variant pretty much exclusively, and is often called "xenolf/lego" not just "lego" -- and just because the four letters "lego" are in the name wouldn't in any reasonable sense make it in violation.

It's all speculation until something happens. I'll close the issue since, unless something really does come of it, there's nothing actionable here except to speculate. Thanks!

**Comment by mslinn** [comment]
You folks have developed an excellent project. I blogged about it [here](https://mslinn.com/blog/2023/03/02/lego.html).

However, you should heed the warning provided by @lpar. I blogged about that [here](https://mslinn.com/blog/2023/03/03/lego-tm.html).

**Comment by ryandesign** [comment]
I noticed that [there is a port called lego in MacPorts](https://ports.macports.org/port/lego/details/). I assumed it was related to the bricks made by the LEGO Group but then discovered it was this project instead. This demonstrates that your project name causes confusion.

Your software is [available in dozens of other software repositories under the name lego](https://repology.org/project/lego/packages). By claiming this name in these repositories, you hinder others, such as the LEGO Group, in distributing software using that name in the future.

The LEGO Group has already demonstrated they are interested in creating computer software. They already offer the [stud.io](https://www.bricklink.com/v3/studio/main.page) software.

You should rename your project now and not wait until you are forced to do so by legal action. If you announce a naming transition and coordinate with the maintainers of your software in the various repositories, you can ensure that it goes smoothly. On the other hand, if your repository is taken down for trademark infringement and you have to rush a naming change, that will be stressful for you and will inconvenience your users.

**Comment by ldez** [comment]
This project exists for 10 years, and used by a lot of companies: I mean that we are visible since a long time.

There is nothing that is related to bricks or the brand inside the documentation or the code, there are no ambiguities.

The name of the organization is `go-acme` not `lego`.

There are hundreds (maybe thousands) of repositories called `lego` or with `lego` in their names that are not owned or related to the company.

The origin of the acronym is related to a clear element: **L**et's **E**ncrypt **Go**

If there is a trademark issue, and we don't think so, asking before taking legal action seems like a more logical and less costly approach for everyone.

If there is a trademark issue, the company can contact us through social network or email.

We are not responsible for external package naming: the packagers can use something like `goacme-lego` instead of `lego`.

:thinking: Maybe Warner Bros will sue us and IETF and Let's Encrypt for using the [ACME](https://en.wikipedia.org/wiki/Acme_Corporation) acronym.

This is just a joke in order to relax the situation a little.

I lock the discussion because only the company can talk about this topic.
