### ISSUE TITLE
Your Docker Setup for Boulder

### ISSUE THREAD

**Issue by influx6** [xenolf/lego#499]
Good day, just wish to get your insight in how you setup your boulder running on docker. I had boulder running with docker, even after exposing the ports `5001` and `5002` on docker, i still see `connection refused` when boulder tries to run it's validation. 

See below 

```dns-srv: Query -- [com.] CAA
dns-srv: Query -- [mydomain.com.] A
dns-srv: Query -- [mydomain.com.] AAAA
dns-srv: Query -- [mydomain.com.] CAA
```

```I094851 boulder-va HTTP request to http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo failed. err=[&url.Error{Op:"Get", URL:"http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo", Err:(*net.OpError)(0xc4201c9b30)}] errStr=[Get http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo: dial tcp 127.0.0.1:5002: connect: connection refused]```

```I094851 boulder-va [AUDIT] Checked CAA records for mydomain.com, [Present: false, Valid for issuance: true]
I094851 boulder-va HTTP request to http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo failed. err=[&url.Error{Op:"Get", URL:"http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo", Err:(*net.OpError)(0xc4201c9b30)}] errStr=[Get http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo: dial tcp 127.0.0.1:5002: connect: connection refused]
I094851 boulder-va [AUDIT] Validation result JSON={"ID":"hyovGELAKgj21WbWHyaDSb8Dmn9avHcidg5gaPcVBhc","Requester":2,"Hostname":"mydomain.com","ValidationRecords":[{"url":"http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo","hostname":"mydomain.com","port":"5002","addressesResolved":["127.0.0.1"],"addressUsed":"127.0.0.1"}],"Challenge":{"id":17,"type":"http-01","status":"invalid","error":{"type":"connection","detail":"Fetching http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo: Connection refused","status":400},"token":"qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo","keyAuthorization":"qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo.-rNg0ollukXW1vPZLS3AE9YNaf91w9NaxLPgChhekcY","validationRecord":[{"url":"http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo","hostname":"mydomain.com","port":"5002","addressesResolved":["127.0.0.1"],"addressUsed":"127.0.0.1"}]},"RequestTime":"2018-03-12T09:48:51.756965943Z","ResponseTime":"0001-01-01T00:00:00Z","Error":"connection :: Fetching http://mydomain.com:5002/.well-known/acme-challenge/qfst_k1H8Fbaqs2BO37IZHtY3xQGzw_YqwP3TASt7Xo: Connection refused"}
I094851 boulder-va Validations: {ID:hyovGELAKgj21WbWHyaDSb8Dmn9avHcidg5gaPcVBhc Identifier:{Type: Value:} RegistrationID:2 Status: Expires:<nil> Challenges:[] Combinations:[] Wildcard:false}
I094852 boulder-wfe JSON={"Endpoint":"/acme/challenge/hyovGELAKgj21WbWHyaDSb8Dmn9avHcidg5gaPcVBhc/17","Method":"GET","UserAgent":"Go-http-client/1.1 (darwin; amd64) xenolf-acme","Code":202,"Extra":{"AuthorizationStatus":"invalid","ChallengeType":"http-01","Identifier":{"type":"dns","value":"mydomain.com"}}}
I094852 boulder-wfe JSON={"Endpoint":"/acme/authz/hyovGELAKgj21WbWHyaDSb8Dmn9avHcidg5gaPcVBhc","Method":"POST","Errors":["400 :: malformed :: Error deactivating authorization :: only valid and pending authorizations can be deactivated","\u0026errors.BoulderError{Type:2, Detail:\"only valid and pending authorizations can be deactivated\"}"],"Requester":2,"Contacts":["mailto:yours@yours.com"],"UserAgent":"Go-http-client/1.1 (darwin; amd64) xenolf-acme","Code":400,"Payload":"{\"resource\":\"authz\",\"Status\":\"deactivated\"}","Extra":{"AuthorizationStatus":"invalid","Identifier":{"type":"dns","value":"mydomain.com"}}}
```

I wonder if i need to do more setup on the host or the container apart from exposing the ports to both the container and host?

Would appreciate your directions and thoughts.
This is how i run my setup: https://github.com/wirekit/tlsfs/blob/master/makefile#L5

**Comment by w-flo** [comment]
Since this issue came up when I tried to find what I was doing wrong, this might be helpful for anyone using xenolf/lego with docker-compose, but I'm not sure if it's the same problem as yours:

My plan was to define a general lego service in docker-compose.yml and then use "docker-compose run" to execute the required commands. The letsencrypt validation always failed though, because the connection (from letsencrypt to the HTTP server started by lego) was refused, just like in this issue report.

It took me a while to figure out that the port mappings declared in docker-compose.yml are *not* used for commands started through "docker-compose run" because these are considered to be one-off commands. The ports are only mapped for services defined in the .yml file that are started through "docker-compose up" (and similar commands). So I defined a lego-renew service that has a "command: --email bleh --domain blah renew --days 60" line and now "docker-compose up lego-renew" works fine.

**Comment by influx6** [comment]
@w-flo Would be great to a sample if possible.

**Comment by influx6** [comment]
Thanks very much

Best Regards,
Alex A. Ewetumo.

Software Engineer
https://github.com/influx6 (trinoxf@gmail.com, Skype: trinoxf, Tel:
+2349053058679)

**Comment by w-flo** [comment]
So the same thing just happened again after I updated the setup for the new lego cmdline interface (I had wondered why I had this elaborate multi-service setup instead of one simple docker compose service that I could call with whatever cmdline options I needed, so I "simplified" that mess while updating to the new lego flags).

I want to thank myself from 8 years ago for pointing out why this happens, as I had completely forgotten about this.

I now learned about the easy fix that I didn't know about back then: the `--service-ports` cmdline option for `docker compose run`. It will enable the port mapping even when using `docker compose run`. Of course this will only work if port 80 is currently unused on the host, just like before when using the multi-service setup.

I now use this:
`docker compose run --service-ports --remove-orphans lego run --email="..." --domains="..." --path="/certs" --http --renew-days=30`

And a simple docker-compose file with only one lego service:
```
services:
  lego:
    image: goacme/lego:latest
    volumes:
      - cert_store:/certs
    ports:
      - "80:80"
    restart: 'no'

volumes:
  cert_store:
    name: cert_store
```
